version: '3.8'

services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "127.0.0.1:9042:9042"
    networks:
      - nodejs-cassandra-network

#  nodejs-app:
#    build: .
#    container_name: nodejs-app
#    ports:
#      - "3000:3000"
#    depends_on:
#      - cassandra
#    networks:
#      - nodejs-cassandra-network

networks:
  nodejs-cassandra-network:
    driver: bridge
